### ISSUE TITLE
Code completion hint for string.split gives code which fails when followed.

### ISSUE THREAD

**Issue by quanglewangle** [degory/ghul#930] opened 2022-01-07 21:17 UTC
Code completion hint for string.split(  invites (separator: char, count: int, options: StringSplitOptions) -> Ghul.string[]

but

string.split(',') gives red underline and shows error "no overload found for split(Ghul.char), tried Ghul.string.split(separator: Ghul.char[]) -> Ghul.string[]ghūl"

string.split([',') seems to work.

**Comment by quanglewangle** [comment] 2022-01-08 08:07
forgot to say extension is 0.5.3

**Comment by degory** [comment] 2022-01-08 09:18
The issue here is that ghūl doesn't have an equivalent to C#'s `params`

The signature for System.String.Split() is a bit odd - it doesn't actually have the overload you're expecting (see [String.Split](https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=net-6.0)), and the ghūl extension isn't offering it

In C#, when you call `"hello".Split('l')`, this works in C# because C# is actually calling the `Split(params char[])` overload in this case. The ghūl equivalent is `"hello".split(['l'])` - i.e. explicitly passing in an array of chars.

I can fairly easily add support for `params` parameters, but to be honest it's low priority because not having it doesn't block access to any part of the SDK or 3rd party libraries.

Related to this, there's also no support for parameter defaults, which means again that some overloads that would work in C# won't work in ghūl without additional explicit parameters.

**Comment by quanglewangle** [comment] 2022-01-08 09:30
That's fine. This works:  hello".split(['l'])

**Comment by degory** [comment] 2022-01-08 10:10
Closing as working as designed, but opened #932 to cover implicit support for `params` parameters

**Closed by degory** 2022-01-08 10:10 UTC
Labels: bug
